### ISSUE TITLE
Requested admin features

### ISSUE THREAD

**Issue by RyanRMurray** [dixonary/amphi-frontend#1]
- Ban/suspend options available next to queued items

- Bucket size tweaking

- Video blacklist maybe

- ~~Remove unsafeperformIO~~

🙏

**Comment by dixonary** [comment]
Thanks Ryan!

Please leave any more administrator tools in comments here.

**Comment by dixonary** [comment]
Hook into the new music server UWCS OAuth grant to pick up exec status for administrators.

**Comment by dixonary** [comment]
@RyanRMurray, re: temporary bans, would the following buttons be sufficient?:

* Remove this video only
* Clear all of a user's queued videos (no suspension)
* 1 hour suspension
* 24 hour suspension
* Indefinite suspension

with a checkbox for "also blacklist this video"?

**Comment by RyanRMurray** [comment]
Those options would be great, thanks.

**Comment by dixonary** [comment]
All implemented as of fd6ffeb588e58fbc542aa7bd1e341039bc782aca :smile:
