### ISSUE TITLE
Connected Count

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#12]
I don't know how feasible this is, but it would be really nice to know approximatly how many people are currently connected.

**Comment by dixonary** [comment]
Agreed! I genuinely haven't got a clue how to implement this even at a high level. Suggestions welcome.

**Comment by the-Bruce** [comment]
I'm afraid I'm not to familiar with the frameworks being used, but my instinct for how it could work is some form of AJAX heartbeat (maybe every 30s) that confirms that you are still connected, and then receives the count of accounts that have sent in a heartbeat within the last couple of minutes. Probably most easily achieved by having last_heartbeat field in the user database storing the timestamp? (Not ideal if you're charged by update, however...).

**Comment by dixonary** [comment]
Yeah, something like that would probably work. Quota/charging is per gigabyte of transfer, but given that we only consumed 10MB total yesterday (a fairly high-traffic day?) I don't think that's too much of a concern.

Setting a heartbeat every 30 seconds seems like a viable option. The issue would be figuring out how to inform the client of who is currently watching. One option would be to resend the `heartbeats` data every time someone heartbeats the server, but that would probably start to consume a lot of bandwidth...

**Comment by dixonary** [comment]
A slightly more suitable approach may be to run a cloud function every 60s which accumulates the heartbeats data into a "viewers" value which then gets propagated to clients. I'll have to check the quotas for running cloud functions but that should be fine.

**Comment by the-Bruce** [comment]
Using SQL as an example, The heartbeat handler might be able to be something like (again, don't know the tools so this could be impossible):
```
UPDATE last_heartbeat = time.now() FROM users WHERE id=$(request.user.id)
return SELECT COUNT(*) FROM users WHERE last_heartbeat>time.now()-<2mins>
```

**Comment by dixonary** [comment]
The nice thing about the toolkit here (Firebase Realtime Datastore) is that it sends updates to us rather than us asking for them. Unfortunately though it does all data manipulations on the client, so there's no 'count' primitive :(

**Comment by the-Bruce** [comment]
Drat. In that case the cloud function may well be the best available option.

**Comment by dixonary** [comment]
Aha! It turns out they have considered this use case:

https://firebase.google.com/docs/reference/js/firebase.database.OnDisconnect

So we should be able to simply maintain a list of connected clients.

**Comment by dixonary** [comment]
This is now done. Note that we only record logged-in user counts!
