### ISSUE TITLE
Time out doing odd stuff

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#14]
![image](https://user-images.githubusercontent.com/44057980/79048474-3135fa80-7c15-11ea-9f8d-b966c370c408.png)
Timed myself out for an hour as a test. It is now showing a negative cooldown?
To be clear, this was after waiting the requisite time for the ban to be lifted

**Comment by dixonary** [comment]
Oops - I did not implement the ending of a suspension...!

**Comment by dixonary** [comment]
Fixed in the cloud! (dixonary/amphi-functions)
