### ISSUE TITLE
Video History Improvements

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#15]
A few things that would make the video history a bit easier to use (I know its WIP, just a few thoughts):

- Consistent ordering: I can't determine what the ordering is, but it doesn't seem particularly useful. Either by last played date (ideally) or alphabetically?
- Search Box: The ability to filter the list to find what you're after would be really useful
- Blacklisted icon: It would be nice to be able to tell at a glance whether the song is blacklisted
- More width: Would it be able to change the `max-width` property on this modal to something a little larger? 500px is a touch cramped for many YouTube titles.

**Comment by dixonary** [comment]
I actually just pushed a change which enforces an ordering (by most recently played) on the video list. (It was supposed to be doing so already, but unfortunately there's a bug in the Hooks library I'm using which discards orderings on queries!) 

The other points are definitely worthwhile changes - it is quite hard to navigate at the moment.

**Comment by dixonary** [comment]
Changes made to production:

- The video history is replaced with the 20 most recently played videos. [The idea being that if a video was played before this point, it is not likely that it will need referencing]
- The complete list of blacklisted videos now appears as a separate tab in the admin toolbox.
- The max width of the admin toolbox is now set to 1000px.
