### ISSUE TITLE
Now playing title visually merges with the author when in narrow mode

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#21]
![image](https://user-images.githubusercontent.com/44057980/86491144-d4ecfd80-bd61-11ea-84f3-6bfba9f68a5c.png)
I'd suggest a small amount of padding be inserted between the two to maintain visual distinction.

**Comment by dixonary** [comment]
Some amount of thought should be put into the narrow mode, really. ATM it mostly relies on bootstrap's default behaviour.
