### ISSUE TITLE
Audit log timestamps

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#22]
Sometimes, when going through the audit log, it is really useful to know how the events occur in relation to each other. Having timestamps (perhaps on hover, although if the dialogue is made wider that's less needed) visible would aid that. It might be likewise helpful to see them in the video history as well to get context, but that's less vital.

**Comment by dixonary** [comment]
Good idea! It won't be possible to retroactively get timestamps of course, but I'll make sure new events get tagged with a timestamp and that gets rendered somehow on the client.

**Comment by dixonary** [comment]
Timestamps now appear in the audit log in production. :)
