### ISSUE TITLE
Skip request button

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#26]
With really awful songs, it might be useful for non-admins to request a skip, which would be shown to logged in admins as a count of skip requests to see if many people agree that the music should end. Bonus is that it reduces the feeling of overstepping responsibility when wanting to get rid of something awful posted by the Pres...

Not sure how feasible this is, and is obviously low priority.

This obviously is a peculiarity of online, given users can't just shout at the exec in the room...

**Comment by dixonary** [comment]
Would something like this work:

[Request Skip] button appears as a yellow button for non-admins, like the red one that appears for admins, on the now playing section.

When this happens, the admins receive a popup saying "A skip has been requested for the current video. [Current total: {n}]"

As Amelie suggested in discord, perhaps we may also want an admin variable that sets a minimum quantity (or maybe instead, a minimum % of current viewers, or both?) which causes a song to be skipped automatically.

**Comment by dixonary** [comment]
All implemented as suggested above, except for notifications. The number of active voteskips is always shown to admins (if >0).
