### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#27]
Very minor bug, but the no-video animation no longer resizes with the window. Tested on Firefox 78.3.0esr and chrome 87.0.4280.66 on Debain Testing.

**Comment by the-Bruce** [comment]
Unfortunately, it looks like the entry view also has resizing issues (won't get as narrow as once it did).

**Comment by dixonary** [comment]
That's interesting. I can't replicate! Will investigate further...

**Comment by dixonary** [comment]
Does not seem to be exhibited in firefox current. Closing.
