### ISSUE TITLE
Spontaneous Combufferion

### ISSUE THREAD

**Issue by dixonary** [dixonary/amphi-frontend#28]
In some cases, buffering is known to occur mid-video despite the user having internet access. Playback does not resume for arbitrarily long periods, including until the end of the song in some cases.

I am unable to replicate this, let alone reliably. If anyone else can, please let me know and tell me of the steps taken (if any) to cause the buffering.

Other open questions:

- Does it happen on particular videos, and does it *not* happen on particular videos?
- Does it happen more or less frequently when Amphi is not focused, or when using a particular web browser?
- Does it happen more frequently at certain times of day?
- How long did you have to wait for video to resume?

One suspected cause is that the issue starts when server and client clocks diverge by almost exactly 2 seconds. This may cause the player to seek to a point, only to begin seeking again almost instantly.

Other hypotheses and any further information are greatly welcomed.

**Comment by DavidBarringer** [comment]
Had issue occur at 2 mins (1:59 on video timer) on pretty much any video that gets to that length. 
Buffers until next video starts, or the video time is changed (using scan or pause/unpause).
After manual unpause, video plays fine until completion.
Tested using Chrome. (also Edge and Firefox)

**Comment by Shaadowmaster** [comment]
I've been having the same issue on most songs. Tested on Firefox and Chromium on Linux, both minimised and maximised. Issue occurs even when video quality is set to 144p.

**Comment by dixonary** [comment]
Thanks for letting me know. Again I have absolutely no way of replicating this bug and therefore I cannot begin to diagnose it.

If anyone figures this out, do please let me know.

**Comment by dixonary** [comment]
There is a workaround for this bug in production. Unfortunately, I can't find the code _not_ in production that contains the workaround, so I am going to have to reconstruct it from first principles 😭

**Comment by dixonary** [comment]
Found, and currently worked around in prod - the video seeks to 02:00.01 after buffering at 02:00.
