### ISSUE TITLE
Allow the proposer to skip their own song once it starts playing

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#30]
This is useful if the end of the video contains things like discussion or thanks after the song, that aren't particularly desirable in a music server. This could probably replace the voteskip button to save needing yet another button in the UI.

**Comment by dixonary** [comment]
Yes, this needs doing. (In fact, I thought it was already an option!)

**Comment by dixonary** [comment]
Indeed the backend already supports this: https://github.com/dixonary/amphi-cloud-functions/blob/master/src/index.ts#L521

Just need the button on the frontend.

**Comment by dixonary** [comment]
Closed by https://github.com/dixonary/amphi-frontend/commit/2a9773051137f5cb5ead6379c34ad68960106974
