### ISSUE TITLE
Toolbox User buttons only show on hover

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#33]
The buttons in the video toolbox for user moderation (Clear Queue, Suspend or Ban) only appear when hovering on their parent div. This seems to be unintended, as the song blacklist button immediately above is permanently visible.

Even if it is intentional, it feels a little awkward to use in its current configuration.

Before hover
![image](https://user-images.githubusercontent.com/44057980/139559402-45cc9171-dd9b-41a7-a77d-545c425caa0d.png)
On hover:
![image](https://user-images.githubusercontent.com/44057980/139559412-a702e546-bead-4444-a143-afbb730c27d3.png)

Tested on linux (Debian Testing), with both Firefox 78.14.0esr, and Chrome 95.0.4638.54

**Comment by dixonary** [comment]
Should be fixed in production.
