### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by distributive** [dixonary/amphi-frontend#9]
Add the ability to queue the entirety of a playlist (or the first unique n videos in a playlist)

**Comment by dixonary** [comment]
How should the new-video box react if a video link is provided which is also in a playlist?

Currently it takes only the video.

**Comment by the-Bruce** [comment]
I certainly would prefer it not take the whole playlist in that specific case, as I am regularly cherry-picking songs from a personal playlist. Could it recognise links like `https://www.youtube.com/playlist?list=PLnW10Px7IXesv1QgqhO_I9gA4xXZo8zUT`?

**Comment by dixonary** [comment]
Very doable!

**Comment by dixonary** [comment]
I think this will have to be done in parallel with bucketing changes ( #24 ). The current blocker here is that queueing a song forces a rebuild of the whole bucketing tree and doing this many times in a row (or in parallel, yikes) will cause the server to choke. So a rethink of the whole enqueue process will be needed.

**Comment by dixonary** [comment]
For the interested, the logic for this appears here in `addMetadataAndUpdateGlobalPlaylist`:

https://github.com/dixonary/amphi-cloud-functions/blob/master/src/index.ts#L280

and here in `updateGlobalPlaylist`:

https://github.com/dixonary/amphi-cloud-functions/blob/32f645b13f007fe576ce689286177b8bd084ee9d/src/index.ts#L389

**Comment by dixonary** [comment]
Added in 20f573f.
